### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by wboswall** [icsharpcode/SharpDevelop#578]
I find the syntax highlighting is hard to see. I have tried to change to a brighter color but failed to see any change.  Is there any why to fix it so it will become more easily to see?  Any ideas would be helpful.  Thank yoiu

**Comment by wboswall** [comment]
Sorry I didn't mean to close this thread.  hand was trigger happy.  Will there be an update to support the rest of the support languages C# or not?

**Comment by wboswall** [comment]
Still waiting for a response.

**Comment by siegfriedpammer** [comment]
The 'bracket highlighting' feature is not implemented for C++. In SharpDevelop 4 it should work for C# and VB. In SharpDevelop 5 C# is the only supported language.

The settings are available for all languages, because the highlighting itself is language-independent. The only part that's language-specific is the `IBracketSearcher` implementation, which currently does not exist for any language except C# and VB.

If you want bracket highlighting for any language other than C# and VB, you are welcome to submit a pull request.

**Comment by wboswall** [comment]
Okay, thank you for responding back.  So when you say “submitting a pull request”, does that mean I modify the code to develop my own version or to submit a request to have that implemented by the sharp developers?  I haven’t contributed to a massive project like this one so I am unsure what you mean.  

Regards,

William






Sent from Windows Mail





From: Siegfried Pammer
Sent: ‎Wednesday‎, ‎April‎ ‎8‎, ‎2015 ‎1‎:‎17‎ ‎PM
To: icsharpcode/SharpDevelop
Cc: William Boswall





The 'bracket highlighting' feature is not implemented for C++. In SharpDevelop 4 it should work for C# and VB. In SharpDevelop 5 C# is the only supported language.

The settings are available for all languages, because the highlighting itself is language-independent. The only part that's language-specific is the IBracketSearcher implementation, which currently does not exist for any language except C# and VB.

If you want bracket highlighting for any language other than C# and VB, you are welcome to submit a pull request.
