### ISSUE TITLE
Move WpfDesigner to its own repository

### ISSUE THREAD

**Issue by wileyrya** [icsharpcode/SharpDevelop#596]
Please move WpfDesigner to its own repository so that it can more easily be used outside of SharpDevelop.

**Comment by gumme** [comment]
I also integrate the WPF Designer in another solution, and I do it by adding the existing WPF Designer projects and the other dependencies projects to my other solution.

The only problem I can remember setting it up is GlobalAssemblyInfo.cs is missing if not building entire SharpDevelop first. I have solved this by adding a "PreBuildProject" that copies a GlobalAssemblyInfo.cs into the correct location before building WPF Designer projects.

I see a danger in moving WPFDesigner to a separate repository, as I see it the integration in SharpDevelop would no longer be natural part of the development and testing process, with the risk of the code bases diverging if no one is taking time to synchronize with SharpDevelop and testing it accordingly. And I see the integration in SharpDevelop as a good thing, because it widens the user base and the potential contributors, and with better development tools for WPF the technology will also get a better spread which in turn could make Microsoft more interested in investing in it.

With this in mind, my suggestion is instead to add a project that does the necessary "pre-building" steps, make the XamlDesigner sample project build on a clean checkout, and also add a chapter to the Wiki on how to integrate WPF Designer into another solution.

I would also appreciate if any of the core members could give a statement on which direction they think is the best. If they like my suggestion I can make a pull request with the needed changes.

Not really related to this ticket, but related to integration in other solutions:
If you like me are using SubVersion for your other solution I can recommend that you use the github SVN bridge. I use it to link my github sharpdevelop fork with svn:externals property. Initially there sometimes was some glitches, but the last year or so it have worked perfect (if it's because updated SVN client or improvements on the SVN bridge I do not know).

**Comment by jogibear9988** [comment]
How is the Sync between Avalonedit and SD done? Is every change in AvalonEdit automaticaly merged to SD or has this to be done manualy?

**Comment by gumme** [comment]
Good catch. NRefactory is also separate, so some sort of routine should already be established. Depending on how it's done maybe a breakout is not that bad after all.

**Comment by Rpinski** [comment]
Hi,

we support the idea of extracting WpfDesigner as an SD-independent project. But AFAIK sync with external repositories (for NRefactory, AvalonEdit...) is done manually at the moment. That's far away from a good and stable solution. We have some better alternatives in mind, but would like to postpone the final decision until we all meet together during our [Developer Days](http://community.sharpdevelop.net/blogs/christophwille/archive/2015/01/14/announcing-developer-days-2015.aspx) in May.

**Comment by jogibear9988** [comment]
I would like to see a extra Repo for it! I'd also like to have nuget packages of the XAML Designer!

I also could help with the move or manage the Repo!

**Comment by jogibear9988** [comment]
It will be done in the next days! See: https://github.com/icsharpcode/WpfDesigner
