### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/SharpDevelop#695]
I've read here that SD is discontinued? Is that true? (http://mikemdblog.blogspot.de)

**Comment by linquize** [comment]
No, it is talking about SD will switch to a Roslyn based refactoring library. So it may be more consistent with Visual Studio and possibly provide more functions.

**Comment by jogibear9988** [comment]
ok, when you read "Since #Develop was discontinued...." it can be understood in another way!

**Comment by christophwille** [comment]
The authoritative answer is still this blog post:

http://community.sharpdevelop.net/blogs/christophwille/archive/2014/10/28/sharpdevelop-5-0-final.aspx

As you can see from the recent NuGet checkins, even SD 4.4.x is active as promised.

Correct, there are currently no plans to move to Roslyn (in say a SD 6.0) - and that's why NR6 (the IDE parts like IntelliSense) moved entirely into MonoDevelop. Creating an API abstraction (NR) on top of another API (Roslyn) that no one uses aside from yourself doesn't cut it. (detail: we had a long discussion - and the gist was that we expect that every new Roslyn version will chip away at the API surface of NR till it is nothing more than a level of indirection. And what's the point of that - adding a layer that adds no value)

Mike's knack for words leaves to be desired, but hey, how can a Xamarin blog post be authoritative for SharpDevelop in the first place?

**Comment by mkrueger** [comment]
But it would be cool if #Develop will move to roslyn. The thing is that maintaining NR is a very time consuming task - so it needs to move. 

That's why moving to roslyn ìs the way into the future. If someone  would pick up that task it would be awesome. SharpdDevelop IS open source - which means it'll stay.

Maybe discontinue is the wrong term - I ment 'no plans for moving to roslyn from the core team' which is in fact a kind of 'discontinuation' - but it doesn't mean that SharpDevelop won't get new bug fixes.
And it doesn't mean that NR5 doesn't get them as well - I surely have to fix things there and they'll land into the SharpDevelop code base.

But if some people really like SharpDevelop - pick up the task to move the thing to roslyn.
