### ISSUE TITLE
Cannot install NuGet package, dependency on wrong framework version

### ISSUE THREAD

**Issue by niklaslundberg** [icsharpcode/SharpDevelop#698]
I'm trying to install a NuGet package RazorEngine 3.7.0 with the dependencies
Microsoft.AspNet.Razor = 2.0.30506.0 (net40) and Microsoft.AspNet.Razor >= 3.0.0 (net45). The project is using .NET 4.5 and already has Microsoft.AspNet.Razor 3.2.3 installed. I've tested it in both 5.1.0 build 5134 and in version 4.4.2. 

The error message is "Updating 'Microsoft.AspNet.Razor 2.0.30506.0' to 'Microsoft.AspNet.Razor 3.2.3' failed. Unable to find a version of 'RazorEngine' that is compatible with 'Microsoft.Asp.Net.Razor 3.2.3'".

**Comment by mrward** [comment]
Thanks for reporting this. It looks like this bug was fixed in MonoDevelop but the change was not applied to SharpDevelop.

This should now be fixed in the latest builds of SharpDevelop 4 and 5 which are will be available from the [build server](http://build.sharpdevelop.net/buildartefacts) shortly.
