### ISSUE TITLE
Overflow issue 

### ISSUE THREAD

**Issue by Reuged** [icsharpcode/SharpDevelop#744]
![overflow](https://cloud.githubusercontent.com/assets/3947393/12837073/0dd5cec2-cba6-11e5-9705-ab97e521a552.png)

i was trying debug a XNA game source code into the compiler when this happen, i declare all XNA lib's at reference solution before i've started

**Comment by mrward** [comment]
This is the exception your application is throwing when you are debugging. The debugger is showing you there is an unhandled exception in your code. It is not a SharpDevelop bug.

**Comment by Reuged** [comment]
i thought it was a bug because in visual studio this overflow never happens

**Comment by mrward** [comment]
I do not believe it is a bug. What is on line 3980 of Main.cs?

**Comment by Reuged** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3947393/12867457/857bd7de-ccd5-11e5-87de-bea3a7fd684f.png)

**Comment by Reuged** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3947393/12867463/b747db14-ccd5-11e5-8ff3-b00541936d13.png)

**Comment by mrward** [comment]
`DateTime.Now.Ticks` returns a long so casting it to an int can throw an overflow exception. That line of code throws the same exception in Visual Studio if I run it in a console project.

If you do not care about the overflow, which looks you do not since you are using it as a random number generator, you can disable the exception by unchecking "Check for arithmetic overflow/underflow" in project options on the Compiling tab in SharpDevelop.

**Comment by Reuged** [comment]
it is a application project

**Comment by Reuged** [comment]
that is odd?!, i built a windows application project and the code ran perfectly on visual studio, but ok i will make proper changes to fix it, thanks for your assist i wish best of luck pal

**Comment by Reuged** [comment]
do you want the source code for a deeper analysis?

**Comment by mrward** [comment]
No need to see the rest of the code. That line is the one that is throwing the overflow exception.
