### ISSUE TITLE
Update nuget

### ISSUE THREAD

**Issue by KeKl** [icsharpcode/SharpDevelop#773]
Hello,

Is it possible to update nuget to a recent Version?

**Comment by jogibear9988** [comment]
which nuget?

**Comment by KeKl** [comment]
Some packages need nuget 2.12 or greater.

**Comment by mrward** [comment]
Updating to NuGet 2.12 should be straightforward. It should just be a case of updating to the latest NuGet 2.12 binaries. Updating to NuGet v3 is not straightforward since the API is completely different and the NuGet addin would need to be mostly rewritten. Updating to NuGet 2.12 should give us support for the latest target frameworks, such as .NET Standard.

**Comment by KeKl** [comment]
I replaced the binary files but I still get the error: "... package requires NuGet client Version 2.12 or above..."

May there has to be something changed in the addin?

**Comment by mrward** [comment]
Not sure why you are replacing the binary files. The change has been made to the latest SharpDevelop 5 available from the [build server](http://build.sharpdevelop.net/BuildArtefacts)
